name: Bug report
description: Report a bug or unexpected behavior.
title: "[BUG]: <Short description of the bug>"
labels: ["status: in-review", "type: bug"]
assignees: ["Aqusorias"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue. Please fill out the fields below.
  - type: dropdown
    id: state
    attributes:
      label: State of the Extension and RPC
      description: Which of the following best describe the current state of the extension and RPC?
      options:
        - The Extension and the RPC are both working 
        - The Extension is working, but the RPC is not working
        - Both are not working
        - Something else
    validations:
      required: true
  - type: dropdown
    id: problem
    attributes:
      label: Problem Description
      description: With what exactly are you facing problems?
      options:
        - The Extension
        - The RPC
        - Both the Extension and the RPC
        - Something else
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - Linux
        - macOS
        - Other
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Mozilla Firefox
        - Google Chrome
        - Microsoft Edge
        - Opera / Opera GX
        - Vivaldi
        - Brave
        - Other
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please describe your problem in detail.
      placeholder: What exactly is the bug or unexpected behavior you're experiencing?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If possible, add screenshots to help explain your problem.
      placeholder: Paste or drag screenshots here
    validations:
      required: false